import type { Metadata } from "next";
import "./globals.css";
import NetworkErrorProvider from "../components/NetworkErrorProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th">
      <body>
        <NetworkErrorProvider>
          {children}
        </NetworkErrorProvider>
      </body>
    </html>
  );
}
